dist: xenial  # required for Python >= 3.7
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
script: python -m unittest
after_script:
  - coverage erase
  - coverage run -m unittest
  - coverage report --include=logdecorator/* --omit=*/tests/*.py
  - coverage xml
